### ISSUE TITLE
Can't find my node.js install

### ISSUE THREAD

**Issue by gitscosh** [robb-j/nova-yaml-language-server#25]
Currently getting  LanguageServer Failed. Node.js is not installed on your $PATH

But, it is. I'm using NVM to manage my node versions. I echoed my $PATH at the command prompt, and it points to where my node binary is located.

/Users/myname/.local/share/nvm/v16.13.0/bin

Am I missing a setup step or config setting in Nova?  Thanks.

**Comment by robb-j** [comment]
Hey, sorry to hear you’re having an issue. Do other aspects of Nova work with you’re node.js installation, e.g. the built in terminal or other extensions that use node.js (like the JSON or TypeScript extensions)? I personally use [fnm](https://github.com/Schniz/fnm) and I had to specify a special [shell argument](https://github.com/robb-j/dotfiles/blob/5b02c4379aa1ca47cf094e70224cb4043516e8f7/.zshrc#L149) so that It worked with Nova. I’m not sure if there is something similar with nvm? 

If this is a common issue, I’ll update the readme with extra steps for node version managers.

**Comment by gitscosh** [comment]
I will check and report back. I'll try installing a JSON extension and see what happens.

**Comment by gitscosh** [comment]
JSON extension fails to activate, too, claming it can't find npm or node is not on my $PATH but it clearly is. Nova is the only app that can't find it.

**Comment by robb-j** [comment]
Hey, I stumbled on this link: https://library.panic.com/nova/environment-variables I think you need to make sure you configure nvm in the right file for Nova to see it. I just found out my own install wasn't actually setup correctly and it was using an old version of node, oops!

if setting it up that way works, I'll update the docs and improve the error message the extension shows you too.

**Comment by robb-j** [comment]
I've released 1.4.0 which doesn't solve this but should help and point you in the right direction! Please re-open this issue if those steps don't work for you.
